# Implementar el docker-compose.yaml
version: '3'

services:
  db:
    image: postgres:latest
    container_name: boston-postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BOSTON
    volumes:
      - boston-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - T2containers-network

  app:
    image: paulozterra/app:v1.0   
    container_name: boston-flask
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: BOSTON
      DB_HOST: db  
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - T2containers-network

volumes:
  boston-data:

networks:
  T2containers-network:
